"""Core domain models shared by the game engine and rulesets."""

from __future__ import annotations

from dataclasses import dataclass, replace
from enum import Enum
from typing import Final, Mapping

BOARD_POINT_COUNT: Final[int] = 24
BAR_POSITION: Final[int] = 0
OFF_POSITION: Final[int] = BOARD_POINT_COUNT + 1
TOTAL_CHECKERS: Final[int] = 15


class Player(str, Enum):
    """Represent one of the two players in a match."""

    WHITE = "white"
    BLACK = "black"

    @property
    def opponent(self) -> Player:
        """Return the opposing player."""
        return Player.BLACK if self is Player.WHITE else Player.WHITE


class GameMode(str, Enum):
    """Enumerate the supported backgammon modes."""

    LONG = "long"
    SHORT = "short"


class TurnPhase(str, Enum):
    """Describe the lifecycle of a player's turn."""

    WAITING_FOR_ROLL = "waiting_for_roll"
    READY_TO_MOVE = "ready_to_move"
    TURN_COMPLETE = "turn_complete"


@dataclass(frozen=True, slots=True)
class PointState:
    """Store checker ownership for one board point."""

    owner: Player | None = None
    checkers: int = 0

    def __post_init__(self) -> None:
        """Validate that the point representation is internally consistent."""
        if self.checkers < 0:
            raise ValueError("Checker count cannot be negative.")
        if self.checkers == 0 and self.owner is not None:
            raise ValueError("Empty points cannot have an owner.")
        if self.checkers > 0 and self.owner is None:
            raise ValueError("Occupied points must have an owner.")

    def add_checker(self, player: Player) -> PointState:
        """Return a new point with one checker added for the player."""
        if self.owner not in (None, player):
            raise ValueError(
                "Cannot stack on an opposing point without capture."
            )
        return PointState(owner=player, checkers=self.checkers + 1)

    def remove_checker(self, player: Player) -> PointState:
        """Return a new point with one checker removed for the player."""
        if self.owner is not player or self.checkers == 0:
            raise ValueError(
                "There is no checker for the player on this point."
            )
        remaining = self.checkers - 1
        return PointState(
            owner=player if remaining else None,
            checkers=remaining,
        )


@dataclass(frozen=True, slots=True)
class Move:
    """Describe a single checker move generated by the rules."""

    player: Player
    source: int
    target: int
    die_value: int
    captures: bool = False
    bears_off: bool = False

    def __post_init__(self) -> None:
        """Validate point ranges and die values."""
        if not BAR_POSITION <= self.source <= OFF_POSITION:
            raise ValueError("Source point is out of range.")
        if not BAR_POSITION <= self.target <= OFF_POSITION:
            raise ValueError("Target point is out of range.")
        if self.source == self.target:
            raise ValueError("Source and target points must be different.")
        if not 1 <= self.die_value <= 6:
            raise ValueError("Die value must be between 1 and 6.")


@dataclass(frozen=True, slots=True)
class DiceRoll:
    """Store the result of rolling two dice."""

    values: tuple[int, int]

    def __post_init__(self) -> None:
        """Validate the dice tuple."""
        if len(self.values) != 2:
            raise ValueError("Exactly two dice are required.")
        if any(value < 1 or value > 6 for value in self.values):
            raise ValueError("Dice values must be between 1 and 6.")

    @classmethod
    def from_values(cls, first: int, second: int) -> DiceRoll:
        """Create a roll from two integer values."""
        return cls(values=(first, second))

    @property
    def is_double(self) -> bool:
        """Return ``True`` when both dice show the same value."""
        return self.values[0] == self.values[1]

    @property
    def pips(self) -> tuple[int, ...]:
        """Return the die values expanded for doubles."""
        return self.values * 2 if self.is_double else self.values


@dataclass(frozen=True, slots=True)
class TurnState:
    """Track dice, legal moves and progress for the active turn."""

    player: Player
    phase: TurnPhase = TurnPhase.WAITING_FOR_ROLL
    dice: DiceRoll | None = None
    remaining_pips: tuple[int, ...] = ()
    legal_moves: tuple[Move, ...] = ()
    moves: tuple[Move, ...] = ()

    def with_roll(self, dice: DiceRoll) -> TurnState:
        """Start a new move phase from a fresh dice roll."""
        return replace(
            self,
            phase=TurnPhase.READY_TO_MOVE,
            dice=dice,
            remaining_pips=dice.pips,
            legal_moves=(),
            moves=(),
        )

    def with_legal_moves(self, legal_moves: tuple[Move, ...]) -> TurnState:
        """Attach the currently available legal moves to the turn."""
        return replace(self, legal_moves=legal_moves)

    def record_move(self, move: Move) -> TurnState:
        """Consume the die used by a move and append it to the turn history."""
        remaining = list(self.remaining_pips)
        try:
            remaining.remove(move.die_value)
        except ValueError as exc:
            raise ValueError(
                "The move does not match any remaining die value."
            ) from exc
        next_phase = (
            TurnPhase.TURN_COMPLETE if not remaining else TurnPhase.READY_TO_MOVE
        )
        return replace(
            self,
            phase=next_phase,
            remaining_pips=tuple(remaining),
            legal_moves=(),
            moves=self.moves + (move,),
        )

    def finish(self) -> TurnState:
        """Mark the turn as complete when no more moves can be made."""
        return replace(self, phase=TurnPhase.TURN_COMPLETE, legal_moves=())


@dataclass(frozen=True, slots=True)
class GameState:
    """Represent the complete immutable state of a game session."""

    mode: GameMode
    board: tuple[PointState, ...]
    current_player: Player
    turn: TurnState
    bar: tuple[int, int] = (0, 0)
    borne_off: tuple[int, int] = (0, 0)
    winner: Player | None = None
    turn_number: int = 1

    def __post_init__(self) -> None:
        """Validate the board and counter structure."""
        if len(self.board) != BOARD_POINT_COUNT:
            raise ValueError(
                f"The board must contain {BOARD_POINT_COUNT} points."
            )
        if len(self.bar) != 2 or len(self.borne_off) != 2:
            raise ValueError(
                "Bar and borne-off counters must contain two items."
            )
        if self.turn.player is not self.current_player:
            raise ValueError("Turn state player must match the current player.")

    def point(self, point_number: int) -> PointState:
        """Return the state of a point using one-based numbering."""
        if not 1 <= point_number <= BOARD_POINT_COUNT:
            raise ValueError("Point number is out of range.")
        return self.board[point_number - 1]

    def replace_point(
        self,
        point_number: int,
        point_state: PointState,
    ) -> GameState:
        """Return a new state with a single point replaced."""
        board = list(self.board)
        board[point_number - 1] = point_state
        return replace(self, board=tuple(board))

    def bar_for(self, player: Player) -> int:
        """Return the number of checkers on the bar for a player."""
        return self.bar[_player_slot(player)]

    def with_bar(self, player: Player, value: int) -> GameState:
        """Return a new state with an updated bar count for a player."""
        counters = list(self.bar)
        counters[_player_slot(player)] = value
        return replace(self, bar=tuple(counters))

    def borne_off_for(self, player: Player) -> int:
        """Return the number of checkers borne off for a player."""
        return self.borne_off[_player_slot(player)]

    def with_borne_off(self, player: Player, value: int) -> GameState:
        """Return a new state with an updated borne-off counter."""
        counters = list(self.borne_off)
        counters[_player_slot(player)] = value
        return replace(self, borne_off=tuple(counters))

    def switch_player(self) -> GameState:
        """Create the next turn for the opposing player."""
        next_player = self.current_player.opponent
        return replace(
            self,
            current_player=next_player,
            turn=TurnState(player=next_player),
            turn_number=self.turn_number + 1,
        )


def build_board(
    layout: Mapping[int, tuple[Player, int]],
) -> tuple[PointState, ...]:
    """Build an immutable board tuple from a point layout mapping."""
    board = [PointState() for _ in range(BOARD_POINT_COUNT)]
    for point_number, (owner, checkers) in layout.items():
        if not 1 <= point_number <= BOARD_POINT_COUNT:
            raise ValueError("Point number is out of range.")
        board[point_number - 1] = PointState(owner=owner, checkers=checkers)
    return tuple(board)


def _player_slot(player: Player) -> int:
    """Return the tuple index assigned to a player."""
    return 0 if player is Player.WHITE else 1
